name: completion
version: 0.2.2
description: A packaged to add shell command completion to your Dart application
homepage: https://github.com/kevmoo/completion.dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.4.0
  logging: ^0.11.0
  path: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.2.0
  test_process: ^1.0.1

executables:
  shell_completion_generator: null
